version: '3'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
        - TZ=America/Chicago
  ui:
    build: ui
    ports:
        - "8081:8080"
    environment:
        - TZ=America/Chicago
  redis:
    image: "redis:alpine"   
